# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rolo < Formula
  desc "Rolo - Roll your own logic"
  homepage "https://github.com/garrettkrohn/rolo"
  version "1.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/garrettkrohn/rolo/releases/download/v1.0.6/rolo_Darwin_x86_64.tar.gz"
      sha256 "93d97d7fb7445ce0867959a5f61d3d4e152b34b3106712c16602f2e1095df979"

      def install
        bin.install "rolo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/garrettkrohn/rolo/releases/download/v1.0.6/rolo_Darwin_arm64.tar.gz"
      sha256 "869fbc5351cb895dfc759f4ae6dde96ca7ad38e74573a5734c3afa08ad97dd27"

      def install
        bin.install "rolo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/garrettkrohn/rolo/releases/download/v1.0.6/rolo_Linux_x86_64.tar.gz"
      sha256 "1c6cc3f56d2fb58719530f55bf876afc28405181a9015cc6de6c260d70f86f46"
      def install
        bin.install "rolo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/garrettkrohn/rolo/releases/download/v1.0.6/rolo_Linux_arm64.tar.gz"
      sha256 "fe48dd90786deebc41650e1718c09dcbb1f852555ee878c366d79b54a7996958"
      def install
        bin.install "rolo"
      end
    end
  end
end
