# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rolo < Formula
  desc "Rolo - Roll your own logic"
  homepage "https://github.com/garrettkrohn/rolo"
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/garrettkrohn/rolo/releases/download/v1.0.5/rolo_Darwin_x86_64.tar.gz"
      sha256 "48114af8a2dee5d726619f57bd69339f9b94524b381a60b910fb13256609433f"

      def install
        bin.install "rolo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/garrettkrohn/rolo/releases/download/v1.0.5/rolo_Darwin_arm64.tar.gz"
      sha256 "512e5abd2cba6e939d217b514e1eb109035bd740295c6f1bc08102c589ceba3d"

      def install
        bin.install "rolo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/garrettkrohn/rolo/releases/download/v1.0.5/rolo_Linux_x86_64.tar.gz"
      sha256 "dcc19b7181af315b535bbad380792c6d9d974a9475a79b612d2d6db1f5299b60"
      def install
        bin.install "rolo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/garrettkrohn/rolo/releases/download/v1.0.5/rolo_Linux_arm64.tar.gz"
      sha256 "113042731beabe20dafcb869b578a870090448b05468e723d6d8a62480dfbfb1"
      def install
        bin.install "rolo"
      end
    end
  end
end
