# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rolo < Formula
  desc "Rolo - Roll your own logic"
  homepage "https://github.com/garrettkrohn/rolo"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/garrettkrohn/rolo/releases/download/v1.0.4/rolo_Darwin_x86_64.tar.gz"
      sha256 "b0c3e0a213155b3b160286cb799b56949a21a4a22d8bfcb775eb34b97e6fdf95"

      def install
        bin.install "rolo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/garrettkrohn/rolo/releases/download/v1.0.4/rolo_Darwin_arm64.tar.gz"
      sha256 "de2f5dedd23dcad68b0c9f2bdbacb62ce1dc8e6653b5e953fc488ca31e222517"

      def install
        bin.install "rolo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/garrettkrohn/rolo/releases/download/v1.0.4/rolo_Linux_x86_64.tar.gz"
      sha256 "0f8609362a2d6667636068ca0c210f3a5f48a66d351a93cf290418b80c4118d5"
      def install
        bin.install "rolo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/garrettkrohn/rolo/releases/download/v1.0.4/rolo_Linux_arm64.tar.gz"
      sha256 "f104bcd197180277182aa8f3c86eb51a73d65e00d839a08ed3e12f6ee0cbdda4"
      def install
        bin.install "rolo"
      end
    end
  end
end
